# Generated by Django 3.1.7 on 2021-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210326_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
