# Generated by Django 3.1.7 on 2021-07-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210710_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Logo'), (2, 'Poster'), (3, 'Icon'), (4, 'Banner')], max_length=254),
        ),
    ]
