# Generated by Django 3.1.7 on 2021-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20210710_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fast_delivery',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], decimal_places=0, default=1, max_digits=1),
        ),
    ]
