# Generated by Django 3.1.7 on 2021-07-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20210710_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(choices=[(1, 'Normal'), (1.5, 'Advanced  (+25%)'), (2, 'Complex  (+50%)')], decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1, '1'), (2, '2  (+20%)'), (3, '3  (+35%)'), (4, '4  (+45%)')], decimal_places=0, default=1, max_digits=1),
        ),
    ]
