# Generated by Django 3.1.7 on 2021-07-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20210710_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(choices=[(1.0, 'Normal'), (1.25, 'Advanced  (+25%)'), (2.0, 'Complex  (+50%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
