# Generated by Django 3.1.7 on 2021-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20210711_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.DecimalField(choices=[('Logo', 1), ('Poster', 2), ('Icon', 3), ('Banner', 4)], decimal_places=0, max_digits=1),
        ),
    ]
