# Generated by Django 3.1.13 on 2021-07-11 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20210711_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.DecimalField(choices=[(1, 'Logo'), (2, 'Poster'), (3, 'Icon'), (4, 'Banner')], decimal_places=1, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1, '1'), (1.2, '2  (+20%)'), (1.35, '3  (+35%)'), (1.45, '4  (+45%)')], decimal_places=1, default=1, max_digits=3),
        ),
    ]
