# Generated by Django 3.1.13 on 2021-07-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_auto_20210711_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1.0, 'Normal'), (1.25, 'Advanced (+25%)'), (1.5, 'Complex (+50%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
