# Generated by Django 3.1.13 on 2021-07-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_auto_20210711_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='complexity',
        ),
    ]
