# Generated by Django 3.1.13 on 2021-07-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_remove_product_complexity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(choices=[(1.0, 'Single'), (1.2, '2  (+20%)'), (1.35, '3  (+35%)'), (1.45, '4  (+45%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
