# Generated by Django 3.1.13 on 2021-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_auto_20210711_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1.0, 'Single'), (1.2, '2  (+20%)'), (1.35, '3  (+35%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
