# Generated by Django 3.1.13 on 2021-07-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_auto_20210711_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(choices=[(1.0, 'Normal'), (1.2, 'Advanced (+25%)'), (1.35, 'Complex (+50%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
