# Generated by Django 3.1.13 on 2021-07-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_auto_20210711_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='complexity',
            field=models.DecimalField(choices=[(1.0, 'Normal'), (1.25, 'Advanced (+25%)'), (1.5, 'Complex (+50%)')], decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1.0, 'Single'), (1.25, '2  (+20%)'), (1.5, '3  (+35%)'), (1.75, '4  (+55%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
