# Generated by Django 3.1.13 on 2021-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_auto_20210711_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variations',
            field=models.DecimalField(choices=[(1.0, 'Single'), (1.25, '2  (+25%)'), (1.5, '3  (+50%)'), (1.75, '3  (+75%)')], decimal_places=2, default=1, max_digits=3),
        ),
    ]
