# Generated by Django 3.1.7 on 2021-07-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0009_auto_20210710_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(editable=False, max_length=32)),
                ('variations', models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], decimal_places=0, default=1, max_digits=1)),
                ('user_description', models.TextField()),
                ('fast_delivery', models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Yes')], default=False, null=True)),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.product')),
            ],
        ),
    ]
