# Generated by Django 3.1.7 on 2021-07-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProduct',
        ),
    ]
